from modules import data_manager
from datetime import datetime

try:
    print("done")
except Exception as e:
    print(e)

